### ISSUE TITLE
Question: is it possible to switch icons?!

### ISSUE THREAD

**Issue by Fabio1988** [WatWowMap/ReactMap#101]
Is it possible exchange gym icons within config?! or only with replacing the images in public folder? :)

https://github.com/nileplumb/PkmnShuffleMap/blob/master/RDM_ALL/misc/ar.png

PkmnShuffleMap is using other image for AR, I think it's more beautiful, what do you say? Can we exchange it ? :)

Best wishes

**Comment by TurtIeSocks** [comment]
Icons will be getting a rework in the near future once UICONS gets their standards figured out so icons will be more flexible in general at that point.
