### ISSUE TITLE
[Feature Request]: Exclude rocket grunt toggle & exclude rocket leader toggle

### ISSUE THREAD

**Issue by Gattaca1** [WatWowMap/ReactMap#1020]
When a pokemon is able to be acquired from both a rocket leader, and a grunt, there is no way to distinguish if you only want to get that mon from the grunt. For example, machop can currently both be got from the fighting type grunt, and also leader cliff. There may only be 10 fighting grunts giving machop in a city, but there could be dozens of leader cliffs. excluding grunt leaders would clean the map up a lot

**Comment by TurtIeSocks** [comment]
Unfortunately, this would be quite a bit of work to implement. I would accept a PR though if anyone is interested.
