### ISSUE TITLE
Database instructions lead to adware website

### ISSUE THREAD

**Issue by MatthewLWheatley** [WatWowMap/ReactMap#1046]
the link to the instruction leads to a adware website. I assume its just had a take over or something it probably shouldnt stay up on the wiki. 
https://www.learn-it-with-examples.com/database/mysql/common-task/create-database-schem-mysql.html
this is the link to clarify.
![image](https://github.com/user-attachments/assets/642479fe-c339-4007-8fc7-edb51cfc35bb)

**Comment by TurtIeSocks** [comment]
Yikes, thanks for the heads up! Fixed it.
