### ISSUE TITLE
Google map URL formatting causes lag on Android

### ISSUE THREAD

**Issue by ZzfaithlezZ** [WatWowMap/ReactMap#1062]
Hi, coming from using another map, I noticed this annoying issue right away when clicking on coordinate URL on the map while on Android phone. The current formatting (https://maps.google.com/maps?q=##.###,##.###) opens Google Maps app which attempts to find a named place for the coordinates. This search process sometimes takes 5-10 seconds and the app spins and spins. The map that I used to use has the URL formatting like https://www.google.com/maps/place/##.###,##,###. Google maps shows the place instantaneously. Please look into this - honestly, this is my only issue with the map, everything else is fantastic. Thanks!

**Comment by TurtIeSocks** [comment]
You'll need to speak with your map admin to change their local config as this is the general repository that's used by maps all around the world and the default isn't either of those: https://github.com/WatWowMap/ReactMap/blob/6b4f7a03365d591964d2877d287df9e5f2a89d88/config/default.json#L915

**Comment by ZzfaithlezZ** [comment]
Got it. thanks. He said he will take a look.
