### ISSUE TITLE
Grey Screen when selecting device assigned to a multi polygon quest instance

### ISSUE THREAD

**Issue by corbindk** [WatWowMap/ReactMap#139]
seems that Reactmap doesn't know how to handle a quest instance that is more than 1 polygon. click the device causes an immediate crash with the following error in console
`TypeError: latlngs is undefined   vendors.ea8890573c185843d28a.js:61425:200`

tested on firefox and chrome with same error. couldn't find any other similarities with the instances causing the crashes

**Comment by TurtIeSocks** [comment]
Can you DM me the instance?

**Comment by TurtIeSocks** [comment]
Fixed in #146
