### ISSUE TITLE
atk/def/sta not showing for MAD

### ISSUE THREAD

**Issue by dkmur** [WatWowMap/ReactMap#145]
![Screenshot_20210813-095517_Chrome](https://user-images.githubusercontent.com/42545952/129323879-28397bf7-b3f0-476c-9224-6e4f778d7993.jpg)

**Comment by TurtIeSocks** [comment]
Have you added roles to the [pokemon]stats section? 
https://github.com/WatWowMap/ReactMap/blob/2f2439c6d20eacd21aa21864fac9e23574182984/server/src/configs/config.example.json#L108

**Comment by dkmur** [comment]
Ignore this idiot, roles were added yet stats option itself was set to false grrrrr
