### ISSUE TITLE
Feature Request - Toggle to Omit Mega PvP Stats

### ISSUE THREAD

**Issue by plinytheelder** [WatWowMap/ReactMap#168]
RM currently uses Ohbem to pull PvP stats which include Megas. However, Megas are banned from GBL, Silph Cups, and pretty much every form of competitive play that I'm aware of. Therefore, it's unnecessary and the majority of players do not care and would prefer to omit them from the map.

Please add either a user toggle, a global toggle, or both to prevent this information from appearing on the map.

**Comment by TurtIeSocks** [comment]
Added in #175
