### ISSUE TITLE
Link Discord Server Main Page

### ISSUE THREAD

**Issue by Swiss-Rainbow** [WatWowMap/ReactMap#173]
Insert links to discord Server / Telegram on the main page where you have to log in

**Comment by lenisko** [comment]
Hmm.. I think instead that, it would be good to have ability to overwrite template.
From technical side: if `overwrite template` exist use it otherwise use `default template`.

So all users could style login page the way they want.

**Comment by TurtIeSocks** [comment]
Resolved in #222
