### ISSUE TITLE
Missing (seen) CP and (caught) level for weather boosted ditto scans from Chuck

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/ReactMap#210]
![image](https://user-images.githubusercontent.com/3511321/135196567-5e372b3a-98ab-45c4-a22f-9c928852b3b8.png)

**Comment by TurtIeSocks** [comment]
Resolved in #260

**Comment by Mygod** [comment]
![image](https://user-images.githubusercontent.com/3511321/150827664-e92913f4-fc5f-476e-9868-b5053fb5fbc2.png)

Inactive IVs should not be shown to the end user as caught IV will be different. I recommend keeping the level/cp line and removing the IV line.
