### ISSUE TITLE
Feature Request : Paypal Button

### ISSUE THREAD

**Issue by bbdoc** [WatWowMap/ReactMap#256]
Please allow adding a configurable Paypal button for donations to the map.

**Comment by TurtIeSocks** [comment]
This currently exists in the message of the day 2.0 feature recently added.

**Comment by bbdoc** [comment]
I'm speaking about adding a permanent button on the page (just like PMSF has it in the header) not about having a button in a pop-up message. MOTD will only allow you to add a permanent message with a button but it will the  pop-up every time the user opens the page which is pretty disturbing.

**Comment by TurtIeSocks** [comment]
As mentioned on Discord, suggestions are currently closed but PRs are welcome 😊

**Comment by TurtIeSocks** [comment]
Reopening since scope has been clarified.

**Comment by versx** [comment]
> As mentioned on Discord, suggestions are currently ~closed~ on hold but PRs are welcome 😊

Best response, ever.

**Comment by TurtIeSocks** [comment]
Resolved in #278
