### ISSUE TITLE
Asterisk pokemon in filters list missing on disabled queries

### ISSUE THREAD

**Issue by lenisko** [WatWowMap/ReactMap#331]
`Spinda*` is missing when `queryAvailable` is set to `false`.
As some forms are missing in filtering, it's impossible to see them without turning on `All Pokestops` option.

**Comment by TurtIeSocks** [comment]
This has been somewhat resolved with the latest PRs that are always querying available. It's a much safer experience for everyone and since it doesn't do at session init anymore, it's now performant as well.
