### ISSUE TITLE
Pokestop popups are higher than they should with pogoassets icon style

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#347]
![image](https://user-images.githubusercontent.com/9063907/150698353-20d6d185-ca8b-4bf4-8834-c0bc83b7cb48.png)

**Comment by TurtIeSocks** [comment]
https://github.com/WatWowMap/ReactMap/wiki/4.-Icons-Configuration

Popup offsets exist for this reason.

**Comment by kamieniarz** [comment]
Of course it is... 🤦 Thanks
