### ISSUE TITLE
"The migration directory is corrupt"

### ISSUE THREAD

**Issue by svenberg** [WatWowMap/ReactMap#352]
On current latest main (f49c4d1) I receive the following output in error log when restarting the PM2 job after yarn build:

`The migration directory is corrupt, the following files are missing: 20220116023217_gym_tracking.cjs
Error: The migration directory is corrupt, the following files are missing: 20220116023217_gym_tracking.cjs
    at validateMigrationList (/home/ReactMap/node_modules/knex/lib/migrations/migrate/Migrator.js:564:11)
    at Migrator.latest (/home/ReactMap/node_modules/knex/lib/migrations/migrate/Migrator.js:70:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/home/ReactMap/node_modules/knex/bin/cli.js:232:32)
error Command failed with exit code 1.
error Command failed with exit code 1.`

I tried searching for the file in the repo but could not find it, so I could not try to manually add that file.

**Comment by lenisko** [comment]
https://github.com/WatWowMap/ReactMap/commit/a4e3e3eeae6c2bbfd9501a645575aa983416e07d#r64540897

**Comment by TurtIeSocks** [comment]
@svenberg let me know if the instructions that @lenisko mentioned work for you so I can close this.

**Comment by svenberg** [comment]
@lenisko This works. I was on the user-gym-badges branch before, that explains why I had to go to develop branch. Thank you!
Can be closed.
