### ISSUE TITLE
Disabling lvl 51 pvp doesn't disable the glow and pvp badge

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#357]
This is how it looks like with `Level 51 PVP Stats` enabled:
![image](https://user-images.githubusercontent.com/9063907/151321013-cd7407dc-8e4b-47bc-b2d8-081cff0f774c.png)

This is how it looks like with `Level 51 PVP Stats` disabled (page reloaded just in case):
![image](https://user-images.githubusercontent.com/9063907/151321102-5ebee064-ad13-4c9f-bab7-4e03f217f809.png)

**Comment by TurtIeSocks** [comment]
Resolved in #452
