### ISSUE TITLE
Login page has a horizontal scroll bar after latest commits

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#359]
Clean login page without any components. 
![image](https://user-images.githubusercontent.com/9063907/151322590-905cdb52-2177-4269-9d40-1a6bbc14056b.png)

Expanding languages list makes it disappear
![image](https://user-images.githubusercontent.com/9063907/151322632-24fb831b-b8bb-48e6-93be-634c886c454f.png)

Screen resolution: 1920x1080, tested on Chrome and Firefox

**Comment by TurtIeSocks** [comment]
Fixed in #385
