### ISSUE TITLE
Quest Icons Bounce Around

### ISSUE THREAD

**Issue by plinytheelder** [WatWowMap/ReactMap#362]
One of the recent commits broke Quest icon placement. They used to remain static and stay in place. However, now they shift up when you enable Invasions.

![image](https://user-images.githubusercontent.com/25189524/151413615-f68c9387-b071-4912-b904-ff856ddb5820.png)

**Comment by kamieniarz** [comment]
This issue also affects pokestop popups when invasions and quests are both enabled

**Comment by plinytheelder** [comment]
any idea how to fix this? it's really bugging me.

**Comment by TurtIeSocks** [comment]
https://github.com/WatWowMap/ReactMap/pull/428

**Comment by TurtIeSocks** [comment]
I consider this resolved in #428 for custom icon implementations.
