### ISSUE TITLE
Access lost - popup

### ISSUE THREAD

**Issue by lenisko** [WatWowMap/ReactMap#365]
Add popup with information `You've been logged out. Most likely your role/permissions has changed. Please login again` or something like that once there's a change on user perms/roles.

Backend is responding with empty data after we lose privileges. Maybe changing HTTP status of response and handling it on front would be enough.

**Comment by BoB3R** [comment]
Hello, I did work around and placed in in motd. Everyone who don't have access got information that they aren't subscribers or it expired.

**Comment by lenisko** [comment]
It's more about taking an action in the moment of losing user privileges. At this moment, POI are disappearing and are no longer spawned, but no refresh is done. After manual refresh, login screen is present.

Leaving a task for self/other reference, but thanks for constructive workaround :)

**Comment by TurtIeSocks** [comment]
Resolved in #448
