### ISSUE TITLE
Pokemon - Filter - Disable PVP on Map with Silder

### ISSUE THREAD

**Issue by pjorritsma** [WatWowMap/ReactMap#368]
Would it be possible to add a slider in Pokemon menu as of 100%iv to disable the PVP Pokemon on the map. Some users request this feature as they only want to see hundo's (100IV) pokemons. 

## Current Behavior
No possible to disable PVP pokemon on the map. 

## Possible Solution
A slider as 100%IV to turn PVP Pokemon ON and OFF.

**Comment by kamieniarz** [comment]
![image](https://user-images.githubusercontent.com/9063907/151576473-05b3663a-070f-42d2-8390-2c9940f4c4f7.png)
That should do the job

**Comment by ReuschelCGN** [comment]
max rank = 0 ??
