### ISSUE TITLE
Poracle (webhook) available lures filter issue

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#376]
All lures should be available
![image](https://user-images.githubusercontent.com/9063907/151635187-3a2c7c95-9d64-4a66-a415-8b3b4956d246.png)

**Comment by Petap0w** [comment]
If you tick `Available` on the left (like here) it'll give the choice only among what's _currently available on your map_

**Comment by kamieniarz** [comment]
Isn't `Available` for whatever is available in game currently, not on map? After 10pm I also see raid bosses in available. Same with quests rewards after midnight

**Comment by TurtIeSocks** [comment]
Available is whatever is in your db.

**Comment by kamieniarz** [comment]
And I think it makes no sense when it comes to Lures. That's why I opened this issue
