### ISSUE TITLE
Close all kinds of windows and menus with ESC button

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#380]
I had some reports from my users that this solution would be rly handy and I agree on that - it's way easier to close window/menu with ESC button than clicking close/X

**Comment by lenisko** [comment]
The main audience is using mobile browsers to browse the map. I think it would be useful only on options and advanced menus, as the popups are easy to hide by clicking somewhere else.

**Comment by kamieniarz** [comment]
I'm on mobile but iirc desktop users can't close windows by clicking somewhere else, right? And I think is should stay that way. ESC as an addition would just be handy and yes I agree that options and advanced menus should be the target

**Comment by lenisko** [comment]
> I'm on mobile but iirc desktop users can't close windows by clicking somewhere else, right? And I think is should stay that way.

They can, but only popups on the map. Not advanced menus and other kind.

**Comment by svenberg** [comment]
+1 on this. I keep pressing ESC all the time to close.

**Comment by TurtIeSocks** [comment]
Resolved in #431
