### ISSUE TITLE
Unnecessary scrollbar in user profile menu in gym badge tab

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#381]
Visible on desktop only
![image](https://user-images.githubusercontent.com/9063907/151677016-152527c3-070a-4086-bd7e-c3dbc9c5dbb7.png)

**Comment by TurtIeSocks** [comment]
React Window is just too much of a pain to deal with this. Different browsers treat it differently, it can only be set with actual sizes, not %s. I've already spent way too many hours trying to size it. I will accept PRs if someone knows how to better manage it but it's beyond me at this point.
