### ISSUE TITLE
Profile images for the Perms that are arrays

### ISSUE THREAD

**Issue by unseenmagik** [WatWowMap/ReactMap#387]
Current user permissions granted are shown In the users profile. 
The images for these perms are stored in `ReactMap/public/images/perms`

The permissions that do not display an image, which are "Area Restrictions" and "Poracle Alerts" are those in the config that are of an array.

Possible to add custom support to allow assigning an image to these permissions so we do not see a blank box within the profile?

![unknown](https://user-images.githubusercontent.com/30931287/152500431-579f443e-598d-443a-8f01-44bac1cc6b99.png)

**Comment by TurtIeSocks** [comment]
Resolved in #416
