### ISSUE TITLE
Changing pvp tracking values duplicates entries in Poracle settings

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#399]
This is what I have:
![image](https://user-images.githubusercontent.com/9063907/154730377-1be1d018-c1c0-4df7-8645-a2c0b0573b31.png)
When I edit this tracking and remove cap by example, entry doesn't get modified but duplicates original one with changes:
![image](https://user-images.githubusercontent.com/9063907/154730516-9d31af31-1bd6-492a-8f81-f6d72d0eeddf.png)

I tried that with single mons and looks like this issue also affects them. Issue doesn't only affect cap, rank also and proly more.

**Comment by TurtIeSocks** [comment]
This isn't a ReactMap issue. Duplication checks are handled by Poracle.
