### ISSUE TITLE
Map stops loading while following user location

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/ReactMap#402]
![image](https://user-images.githubusercontent.com/3511321/155016516-2bace541-f9ad-45fd-bfd7-6868fec87b22.png)

Whenever map moves, a new request is sent. Since the requests keep piling up, the latest request never gets finished and the map stop responding.

Bug introduced by this commit: https://github.com/WatWowMap/ReactMap/pull/264/commits/a9c31310ac524622c39d98d7b4064540f3ac9a2c

**Comment by clburlison** [comment]
@Mygod Is this still valid? Not something I've ran into on my end and this one has been open for over a year.

**Comment by Mygod** [comment]
Fixed in https://github.com/WatWowMap/ReactMap/pull/692 since nobody else bothered to fix it. Let me know if this is still happening.
