### ISSUE TITLE
Restrict areas without auth

### ISSUE THREAD

**Issue by MC0R3** [WatWowMap/ReactMap#404]
Hi all,

Not really an issue, more a suggestion; but it would be nice to also have the option to restrict areas if authentication is disabled. For multi-domains or just in general, it would be a great option to have to just show one specific area without a required login.

Thanks for your hard work though, appreciate the effort and time going into this project :)

**Comment by bbdoc** [comment]
Even better would be to be able to restrict certain elements on an area.

E.g. : 
- on area 1 I want to display only raids if not connected
- on area 2 I want to display raids and pokemon if not connected
- ...
-

**Comment by lenisko** [comment]
Sounds good! Anyone interested? I lack time atm...

**Comment by TurtIeSocks** [comment]
Added in #427
