### ISSUE TITLE
Improve `Scan Areas` tab functions

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#440]
1. Option to assign smaller areas to bigger ones and create sections, eg. section called New York with areas assigned to it: Manhattan, Harlem, Chinatown, etc. Each smaller areas could be in columns instead of one big column long af 😬 Example below taken from PMSF 
![image](https://user-images.githubusercontent.com/9063907/161849107-5dd76169-0fb2-4fe2-82f7-bd83f6b1f0ba.png)
2. Add specific areas to role perms so roles with area restrictions won't see areas that are outside of their area

**Comment by TurtIeSocks** [comment]
Also resolved in #518
