### ISSUE TITLE
Users without full access can't view pokestops

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#461]
I have setup in which users without special access have access to perms: map, gyms, gymBadges, pokestops, portals, submissionCells, nests, scanAreas, weather
All of these work except pokestops. Fun fact is I can view the ones with AR task on them. I simply can't view all of them

**Comment by TurtIeSocks** [comment]
Try latest `develop` and report back.

**Comment by kamieniarz** [comment]
All good now, thank you!
