### ISSUE TITLE
Weather Enhancement

### ISSUE THREAD

**Issue by plinytheelder** [WatWowMap/ReactMap#470]
Would be nice if the global weather icon displayed info "onclick" like the s2cell icon does.

Note, I looked through the code to find something to copy-paste but wasn't sure where it was.
![image](https://user-images.githubusercontent.com/25189524/165161872-2d475512-8b95-4cb7-8e78-0081401655d7.png)

**Comment by TurtIeSocks** [comment]
It'd probably have to be a full on modal instead of a Leaflet popup. Not sure if you can rotate popups and even if you can, that isn't a Leaflet market, just a regular div.

**Comment by plinytheelder** [comment]
well, it's such a cool feature that it would be nice if it weren't hidden 😃

**Comment by TurtIeSocks** [comment]
<img width="386" alt="Screen Shot 2022-04-25 at 6 49 23 PM" src="https://user-images.githubusercontent.com/58572875/165187128-933265f0-ddc8-492a-96e7-128f9bdae851.png">
This is what I mean

**Comment by plinytheelder** [comment]
sign me up!

**Comment by TurtIeSocks** [comment]
https://github.com/WatWowMap/ReactMap/pull/471 Ready for testing

**Comment by plinytheelder** [comment]
works as intended
