### ISSUE TITLE
Minor annoyance with the available-filter's behavior

### ISSUE THREAD

**Issue by Ninjasoturi** [WatWowMap/ReactMap#492]
I filter out some unwanted raid bosses. I have quite good coverage of the area that I scan so it is highly probable that hatched ? eggs aren't on available filters. When a raid hatches on a gym at the edge of the scan area, it is hidden from my map and I can only make it visible with All Gyms or Quick Select even though I would like to have them visible all the time

**Comment by TurtIeSocks** [comment]
Just to clarify, we're talking about hatched raids that don't yet have a determined raid boss, right?
![image](https://user-images.githubusercontent.com/58572875/168698620-17959195-b36e-4ebe-8061-b0dc73dd001a.png)

These should appear if the respective egg tier is selected in the advanced menu?

**Comment by TurtIeSocks** [comment]
They should still appear when the respective egg is selected in the menu, but regardless, I guess #493 solves this, if you want to give it a try.

**Comment by Ninjasoturi** [comment]
Sorry, I forgot! I tested it now, and the unknown hatched eggs are back in the filters and the gyms show up on map. There is still a minor issue with filtering them out.

When raids selector is on and all gyms off, everything works as expected.

When raids and all gyms selectors are both on, the unknown hatched eggs don't get filtered out if I uncheck them from advanced menu. Only if I uncheck the respective tier's normal egg (the unknown hatched egg has no effect).

**Comment by TurtIeSocks** [comment]
Hmm maybe this is a MAD specific issue...

**Comment by Ninjasoturi** [comment]
Oh right. If you can't reproduce, it could also be the dual db setup I am running.

**Comment by TurtIeSocks** [comment]
Do you have overlap between RDM and MAD? Dual database only has some "consistency issues" when there's overlap between multiple database sources.

**Comment by TurtIeSocks** [comment]
I would try switching to only one and see if it resolved. This is likely an issue related to the gyms not being updated.

**Comment by Ninjasoturi** [comment]
I tried with only MAD db and the issue persisted. My RDM isn't working at the moment, I had a minor case of SSD failure. But I tried adding `&& gym.raid_battle_timestamp > safeTs` to the raid level condition in `/server/src/models/Gym.js#241` and at a quick glance that seems to have fixed it. I don't know if it breaks something else though 😅

**Comment by TurtIeSocks** [comment]
Sounds good, i'll check it out, thanks for the assist!

**Comment by TurtIeSocks** [comment]
I believe this may have been resolved, but since you're not using MAD anymore (IIRC), I'm going to close this. If someone else is experiencing it, feel free to reopen.
