### ISSUE TITLE
Make pokemon filtering simple

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#501]
**Motivation**
Pokemon filtering is complex which makes it hard to do simple things. As an example first thing user would want to do is enable hundos/top1 pvp and exclude some mons by unselecting them somehow or excluding them from mons' context menu `...` on map. But it's not possible to do so on map and as default all mons in advanced menu are disabled. That's very confusing for new users and I keep getting questions about that. In fact to disable specific mons user has to go to advanced, enable all mons, apply filters to all mons, disable unwanted mons and save. That's a lot of steps so why not make it way more simple?

**Solution**
![image](https://user-images.githubusercontent.com/9063907/170101597-d6916b54-2d99-46e8-992d-77262d92dd45.png)
Screenshot from above shows fliter options that we currently use - it's known for us, it's complex, it gives a lot of options but it's not simple. I added two switches: one for enabling all mons that would overwrite all filters and simply show all mons (with IV, without IV etc)

![image](https://user-images.githubusercontent.com/9063907/170105369-fb7e2417-23d4-4feb-ad2b-6e856ec27703.png)
Here's what it's all about. When advanced menu is disabled we have simple menu that allows us setting up filters in one tab and in second tab it allows us disable mons (it's ugly on my visualization, I know) just by one click. It's not that complicated as it currently is. Ofc that settings per mon could be removed or replaced with Tt
![image](https://user-images.githubusercontent.com/9063907/170106576-6ed3c706-23cc-4cbc-a867-57841b00ed46.png)
This feature would also be available when advanced menu is disabled. That would simply disable that specific mon type in POKEMONS tab

Both new switches could be added to config file to enable/disable them generally and/or enable/disable them by default on map first use.

**Comment by Dewpg** [comment]
Seconding: the general filtering process is too complex.  The First layer of filters should be simple (IV/GreatLeague/Ultraleague), with the ability to go into further depth that Refines the first filter (or overrides if toggled) (costume, custom IVs).

**Comment by spammer23** [comment]
Would love to see the Exclude button as first step
