### ISSUE TITLE
Improvement and enhancement: enable/disable individual areas.

### ISSUE THREAD

**Issue by tolukolvi** [WatWowMap/ReactMap#505]
Enable or disable shown areas from "scan areas"-menu so that ReactMap stops loading gyms/stops/pokemon etc. from disabled areas. I run a map with 13 areas that have over 11k gyms and over 44k stops. Would be nice to have the possibility to control what areas are loaded. This would be especially useful for people who use mobile phones to view the map.

**Comment by TurtIeSocks** [comment]
Fixed in #518
