### ISSUE TITLE
Feature: Editable Nest Names

### ISSUE THREAD

**Issue by ChaosEmpire** [WatWowMap/ReactMap#517]
I would like to see an admin option to modify nest names, in case nestwatcher isn't able to find the name in osm data

![grafik](https://user-images.githubusercontent.com/16727325/174746138-7a8c1cc1-a1dd-4794-9795-fa42fa437418.png)

**Comment by TurtIeSocks** [comment]
Resolved in #767

**Comment by kamieniarz** [comment]
@ChaosEmpire and anyone else - keep in mind nestwatcher will overwrite in each run all changes made with ReactMap
