### ISSUE TITLE
[Feature Request] 300m Interaction Range

### ISSUE THREAD

**Issue by versx** [WatWowMap/ReactMap#526]
Suggested by one of my users: create 300m interaction range circle (toggleable of course) for the spawned Pokemon when beating a raid.

**Comment by TurtIeSocks** [comment]
@versx should this be tacked on as an additional option for only 300m or should I just make all interaction ranges an adjustable amount in meters?

**Comment by TurtIeSocks** [comment]
I guess this is also related to #499... so same question to @kamieniarz but for 40m on Pokestops.

**Comment by versx** [comment]
> @versx should this be tacked on as an additional option for only 300m or should I just make all interaction ranges an adjustable amount in meters?

I'd say either would be fine in my opinion. If you're referring to users being able to adjust the amount, I'd say no but if it's adjustable for Admins via the config then I think that's perfectly fine.

**Comment by kamieniarz** [comment]
^ I'm fine with it

**Comment by Mygod** [comment]
300m turns out to be variable by event and this is going to be properly supported by #1116. Will be reverting this.
