### ISSUE TITLE
Pokestop layering for quests and invasions.

### ISSUE THREAD

**Issue by AppIe314** [WatWowMap/ReactMap#549]
Pliny posted in #custom-code-injections his method to overlay Pokestop information in a PMSF-eqsue way. Is there any chance we could have this as default behaviour in ReactMap?  

Currently displaying Invasions and Pokestops looks like this:
![invasions-quests](https://user-images.githubusercontent.com/80601216/183123471-4c83a737-3187-4b30-9b0d-3cd24cb467a5.png)

Pliny's overlaying looks like this:
![image](https://user-images.githubusercontent.com/80601216/183123091-4e00b1d7-681a-4d4e-b1fb-91cabdea3b7c.png)

**Comment by TurtIeSocks** [comment]
But...why? This is why the custom code injection and discord template channels exist?

**Comment by plinytheelder** [comment]
Even though it would be cool to have a “Pliny” variable in the config, I do agree with turtle. But glad you’re enjoying my styling!
