### ISSUE TITLE
"Display gym badges always" mode

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#554]
A feature request to have an option to always display gym badge ;) Clicking on badge could display that window to change dym badge
Something like on screen below (taken from my PMSF fork):
![image](https://user-images.githubusercontent.com/9063907/184511889-9b54d1b1-d3cd-4b42-84b2-cc79ec07904f.png)

**Comment by clburlison** [comment]
Not a fan of adding the full image of the badge due to limited space in the model popup on mobile screens. Could make it text in the extra section which would be hidden by default.

**Comment by kamieniarz** [comment]
Looks like it's not going to happen so I'll just close that ;)
![image](https://github.com/WatWowMap/ReactMap/assets/9063907/3304ff5d-16fe-4be3-bb56-2fc9012c7dae)
