### ISSUE TITLE
scanNext is very laggy and buggy

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#555]
I'm pretty sure my gif explains it all. Desktop isn't that bad (but still has issues when I try to move pin to a place where scannext infobar is) but mobile is actually way worse than gif below (I used mobile preview on my PC so it's pretty smooth as for mobile). On some (if not most) devices moving that location indicator is almost impossible - 3 or 4 pin changes and map freezes even on desktop's mobile preview :(
![scannextmobile](https://user-images.githubusercontent.com/9063907/184512131-e201e983-b455-4888-86bb-46be84e6f846.gif)

**Comment by TurtIeSocks** [comment]
This was also resolved afaik.
