### ISSUE TITLE
Pokemon search

### ISSUE THREAD

**Issue by yw2theorycrafter** [WatWowMap/ReactMap#561]
PMSF supports pokemon search, with results shown by distance-from-current-map-center.

It's a nice UX for checking if there are any of some particular mon on the map without having to mess with filters and zoom out, i.e. search pokemon -> Unown should show if there are any unowns (and let you jump to the closest one in a click.)

**Comment by TurtIeSocks** [comment]
I vaguely recall @plinytheelder mentioning the performance was terrible.
