### ISSUE TITLE
Gym occupancy number on icon too small

### ISSUE THREAD

**Issue by yw2theorycrafter** [WatWowMap/ReactMap#563]
The number here:

![6A00745A-85C4-4090-AA11-126E77C80D0C](https://user-images.githubusercontent.com/44895172/188499617-6f6583d8-b942-4a6f-96d3-66acd6de9cda.jpeg)

is too small to read.

**Comment by TurtIeSocks** [comment]
https://github.com/WatWowMap/ReactMap/wiki/06.-Icons-Configuration

You can increase the size of the icons or use any UICONS compatible set that has bigger numbers.
