### ISSUE TITLE
scanNext/scanZone usage log

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#569]
Feature request: an admin log with all users and locations they scanned with scanNext/scanZone. Maybe a heatmap or just a map with pins or so? 

Motivation: monitor usage and potential abuses + monitor potential demands of regular scan areas

I know these things are already in reactmap logs but it's for sure not the best way to catch and agregate these events ;)

**Comment by plinytheelder** [comment]
A discord channel log similar to logins could work. Gives the user, timestamp, and location requested.

**Comment by TurtIeSocks** [comment]
Closing due to being previously resolved.
