### ISSUE TITLE
Add toggle for "Show Polygons"

### ISSUE THREAD

**Issue by AppIe314** [WatWowMap/ReactMap#582]
Make the "Show Polygons" toggle state configuration, maybe add to clientSideOptions. Show Polygons toggle can be locked behind perms so will need to check that perms are respected.

**Comment by TurtIeSocks** [comment]
I believe it's just: https://github.com/WatWowMap/ReactMap/blob/e95b25c2eb77d4267ea6d2aa6341a20d98f6eda0/server/src/configs/default.json#L434

**Comment by AppIe314** [comment]
Thanks. Setting that to true enables the button for everyone to use but the default state of the button is off. I was hoping there'd be a way to have the state be always on.

I have gym/raid visibility on for everyone regardless of roles. Since I enabled scanNow/scanNext there are a now lots of gyms outside my defined scanning areas which can be misleading as people may think I scan those areas. Having Show Polygons always on would be helpful in this case imo

Actually now that I type this maybe I should just find where the button is defined to change the default state?

**Comment by AppIe314** [comment]
Ah yes that did the trick... Silly me.
Thanks for your time!
