### ISSUE TITLE
Telegram login broke after updating to latest dev

### ISSUE THREAD

**Issue by Ninjasoturi** [WatWowMap/ReactMap#592]
Error message:
``2|reactmap  | Fetch.json is not a function Telegram Group: -XXX User: XXX
2|reactmap  | (node:26841) Warning: Accessing non-existent property 'json' of module exports inside circular dependency
2|reactmap  | (Use `node --trace-warnings ...` to show where the warning was created)``

Circular dependency is apparently created by the use of `Fetch` and `fetch`.
/server/src/services/Fetch.js has a class `Fetch` and it's function `fetchJson` is calling `fetch`

**Comment by TurtIeSocks** [comment]
Can you pull with the commit I just pushed up?

**Comment by Ninjasoturi** [comment]
New error `Cannot read properties of undefined (reading 'status')`

**Comment by TurtIeSocks** [comment]
Pushed again. Sorry, I don't have my dev TG setup currently 😓

**Comment by Ninjasoturi** [comment]
No problem! It's working now, thank you!
