### ISSUE TITLE
MOTD for quest scanning

### ISSUE THREAD

**Issue by BoB3R** [WatWowMap/ReactMap#597]
Hello,

I've got users that never visits discord when I post that there will be rescan of quest. I was thinking maybe adding some logic that is device SE1 is assigned to instance Quests1 users will get MOTD "Quest scanning in progress". I know that people might have different instances for example per town, so it would be best to include that logic too zone restriction rights. I hope more or less it is clear what I mean hehe

**Comment by TurtIeSocks** [comment]
Maybe instead of by device, we look at instances? For example, in the config, you could have an array of quest instances that you want to alert users about (or an option for all). If any of those instances are active, with a set interval that's checking the device/instance DB, a MotD template could be generated saying X instances are currently being scanned for quests?

**Comment by BoB3R** [comment]
Yeah that sound good, would be less strain on the DB I think.

**Comment by kamieniarz** [comment]
But what if I use separate device (not mons related) to scan more quests or so? MOTD would be kinda pointless then. I'd rather go with this solution: https://github.com/WatWowMap/ReactMap/issues/464 ;)

**Comment by TurtIeSocks** [comment]
What do you mean? This wouldn't be device dependent, just if any specified quest instances are active.

**Comment by BoB3R** [comment]
I think that he means, that he switch to mons but leave like for example 1 device to continue scanning quests?

**Comment by kamieniarz** [comment]
> What do you mean? This wouldn't be device dependent, just if any specified quest instances are active.

Lets say I scan mon instance with 10 devices that during the night do quests but I scanned 90% of pokestops and during the day I'd like to scan other 10% with additional device when these 10 devices are still scanning mons. MOTD about quest scans in that case is pointless

**Comment by kamieniarz** [comment]
I use rdmass to schedule quest scans and that's why I think issue 464 would be the best option cause rdmass sends notification to announcements channel

**Comment by BoB3R** [comment]
> But what if I use separate device (not mons related) to scan more quests or so? MOTD would be kinda pointless then. I'd rather go with this solution: #464 ;)

That #464 dosn't look back but I would rather have something automatic. When I use rdmass I sometimes don't have time to post it on discord. Plus you got telegram and in house login.

**Comment by kamieniarz** [comment]
> > But what if I use separate device (not mons related) to scan more quests or so? MOTD would be kinda pointless then. I'd rather go with this solution: #464 ;)
> 
> That #464 dosn't look back but I would rather have something automatic. When I use rdmass I sometimes don't have time to post it on discord. Plus you got telegram and in house login.

rdmass posts info by itself ;) just configure it

**Comment by TurtIeSocks** [comment]
> > What do you mean? This wouldn't be device dependent, just if any specified quest instances are active.
> 
> Lets say I scan mon instance with 10 devices that during the night do quests but I scanned 90% of pokestops and during the day I'd like to scan other 10% with additional device when these 10 devices are still scanning mons. MOTD about quest scans in that case is pointless


So you could just exclude that instance from being checked on/reported in a motd?

**Comment by kamieniarz** [comment]
> > > What do you mean? This wouldn't be device dependent, just if any specified quest instances are active.
> > 
> > 
> > Lets say I scan mon instance with 10 devices that during the night do quests but I scanned 90% of pokestops and during the day I'd like to scan other 10% with additional device when these 10 devices are still scanning mons. MOTD about quest scans in that case is pointless
> 
> So you could just exclude that instance from being checked on/reported in a motd?

But it would be scanned each day at night anyway

**Comment by BoB3R** [comment]
> > > But what if I use separate device (not mons related) to scan more quests or so? MOTD would be kinda pointless then. I'd rather go with this solution: #464 ;)
> > 
> > 
> > That #464 dosn't look back but I would rather have something automatic. When I use rdmass I sometimes don't have time to post it on discord. Plus you got telegram and in house login.
> 
> rdmass posts info by itself ;) just configure it

Okay I will try that, but another question will be for #464 how do you clear it MOTD? How long will you want to stay there? I rather don't bother premium users to close MOTD every time they log in as I know for experience it is annoying. Best would be to display once per user. Anyways it is up to @TurtIeSocks what way he wants to go hehe

**Comment by TurtIeSocks** [comment]
Going to close this for now. I think RM is perhaps not the correct tool to alert users automatically of quest rescans
