### ISSUE TITLE
Portals and POI are overlayed by other layers

### ISSUE THREAD

**Issue by zakius** [WatWowMap/ReactMap#601]
Currently various layers are rendered *above* these two making it impossible to click on a Portal or POI when these are enabled.

Layers I confirmed to be causing this issue are:
- L14 cell shading
- Pokestop interaction range
- Lure range
- Gym interaction range
- Gym 300m range

there may be others too

**Comment by TurtIeSocks** [comment]
This map has tons of optional layers. If someone is concerned about it they should disable the others. Arguably, portal/poi circles are the least prioritized compared to all of the ones mentioned, except for L14 cells, which appears to have been fixed since this was opened.

**Comment by zakius** [comment]
I'd argue that POI *may* be low priority (as these are ... exactly what? but probably we can work without these at all), but making Portals not clickable due to non-interactive layers' presence is pretty odd to say the least, though with the L14 issue fixed it's a minor issue now
