### ISSUE TITLE
Make Portal and POI indicators smaller

### ISSUE THREAD

**Issue by zakius** [WatWowMap/ReactMap#602]
It would be useful to have these smaller, decluttering the view and making the actual locations easier to pinpoint. Additionally the current Ingress spacing circles could be added to them as optional feature

**Comment by zakius** [comment]
I mean the area "occupied" by a portal that prevents other portals from appearing (unless something breaks)

**Comment by TurtIeSocks** [comment]
Meant to come back to this but I believe the current radius of the circles is indeed this "spacing" so it's intentional and I don't see why we need to add yet another layer.

**Comment by zakius** [comment]
my reasoning was:
- big circle makes it hard to see the actual position
- big circle may cause clutter when it's not needed and the point alone would suffice
