### ISSUE TITLE
Poracle Areas grouping 

### ISSUE THREAD

**Issue by Fabio1988** [WatWowMap/ReactMap#603]
Pls group them by `group`, like poracle itself does it :)

```
group 1
  city 1
  city 2
group 2
  city 3
  city 4
```

geofence.json in poracle looks like that:
```json
[
  {
    "name": "City",
    "group": "District",
    "color": "#15fa53",
    "id": 0,
    "path": [
      [45.5310989, 13.9896868],
      [45.1704354, 13.3016374],
      [45.1719278, 13.3019486],
      [45.1735944, 13.3026475],
      [45.1754143, 13.30342],
    ]
  }
]
```

@jfberry, is that provided over api?

**Comment by TurtIeSocks** [comment]
Can you DM me your areas file so I can verify?

**Comment by jepke** [comment]
> Can you DM me your areas file so I can verify?
Reactmap uses `parent` where poracle uses `group` to do the same thing. I think thats what @Fabio1988 means

**Comment by jfberry** [comment]
`group` in poracle is a different heading - is `parent` referencing another fence?

**Comment by jepke** [comment]
> `group` in poracle is a different heading - is `parent` referencing another fence?

From my understanding it kinda works the same.
In reactmap i can use a parent name that is a none existing fence so it creates a `group` in Scan Areas menu. When you click the parent/group name it enables/disables all the childs.

But yes in reactmap the parent can be a fence and will be listed as a child as well when parent is set to its own.
