### ISSUE TITLE
Feature Request:  Level 15 S2Cell Layer

### ISSUE THREAD

**Issue by wrinklytesties** [WatWowMap/ReactMap#605]
RM currently has Lv14 and Lv17. I think adding in Lv15 for those who choose to support cell mon through their backend would be beneficial to the user base.  A quick layer view over the center coordinates, allows a user to quickly decide which target areas to loop in order to discover the cell mon in the vicinity.  This can also be useful for those utilizing ScanNext/Zone features for their communities, whereby a layer view provides better visual of the targets surrounding areas.

**Comment by TurtIeSocks** [comment]
I'm mostly not sure where to put them. L14 and L17 live there currently because they interact with Wayfarer stuff, L15 doesn't though. Any suggestions?
