### ISSUE TITLE
[Request] Gray Out Inactive Controls

### ISSUE THREAD

**Issue by versx** [WatWowMap/ReactMap#610]
Small request/suggestion from one of my users to make it more noticeable/prominent. Gray out the PvP rank value elements just like the element labels are currently for the PvP rank filters when disabled/inactive.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1327440/203707983-15b3fca4-564c-4f7b-9417-18f4bec0d0b1.png">

**Comment by TurtIeSocks** [comment]
![Screenshot_20221125-065727.jpg](https://user-images.githubusercontent.com/58572875/203981174-f43cf0cf-fa13-4e7b-8e71-405c993f3641.jpg)

Like this?
