### ISSUE TITLE
Remove Gym from poracle bot

### ISSUE THREAD

**Issue by Zyahko** [WatWowMap/ReactMap#615]
When the Poracle integration has been set up and you view a Gym popup and then go to the 3 vertical dots it has an option to Add Gym to Poracle Bot. Is there a way to get an option to Remove Gym from Poracle Bot if the gym was already added to the user's alerts?

**Comment by Fabio1988** [comment]
Yes go directly to the notification center in RM and remove it from there?

**Comment by Zyahko** [comment]
Yeah that is what I mentioned to the user that brought this up. They made a comment that if there is a quick add button that there should be a quick delete button from the same menu. So I told them I would suggest it.

**Comment by TurtIeSocks** [comment]
Seems reasonable. Just have to think about how to do it. Most of the poracle tracking data is kept separately.

**Comment by TurtIeSocks** [comment]
Resolved in #756
