### ISSUE TITLE
Parent in geojson file breaks "Scan Area menu" when area restrictions is used

### ISSUE THREAD

**Issue by jepke** [WatWowMap/ReactMap#619]
1. When user has no role matching any of the area restrictions all are shown on both the map and in `Scan areas`

Expected behavior (when area restriction is used): Nothing is shown on the map, perhaps a notification popup to contact the admin.
Personal workaround: Create a tiny fake fence and have guild id as role in arearestriction. 

2. When using `parent` in the geojson file in combination with area restrictions the `Scan Area` menu list will stay empty.

Likely cause is that `parent` is prepended to the area name causing a miss match in filtering.
`Suburb` becomes `City-Suburb` in `user.perms.areaRestrictions`
```
"properties": {
        "name": "Suburb",
        "parent": "City"
},
```

Expected behavior: List of areas that are allowed in `Scan areas`

**Comment by jepke** [comment]
When parent property is removed from the geojson files it works as intended. And only shows areas the user has access to.

Likely filtering. objects in the `scanAreas` array become `{parentname}-{areaname}` where its probably looking for `{areaname}`

**Comment by VampireSilence** [comment]
I tried removing parent from the properties, but it didn't work for me.

I noticed that lat/lon are swapped in areas.json. Is it possible that it interferes with the geometry check here:
https://github.com/WatWowMap/ReactMap/blob/91f699ff6e3242d533a879385eac7e8d6f972854/src/services/functions/checkAreaValidity.js#L16 ?

**Comment by jepke** [comment]
> I tried removing parent from the properties, but it didn't work for me.
> 
> I noticed that lat/lon are swapped in areas.json. Is it possible that it interferes with the geometry check here:
> 
> https://github.com/WatWowMap/ReactMap/blob/91f699ff6e3242d533a879385eac7e8d6f972854/src/services/functions/checkAreaValidity.js#L16
> 
> ?

geojson is lon/lat is the correct way https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1

**Comment by TurtIeSocks** [comment]
Hm this was fixed. Not sure why it didn't close on merge.
