### ISSUE TITLE
Event Stops do not respect incident perms

### ISSUE THREAD

**Issue by Fabio1988** [WatWowMap/ReactMap#633]
Event stops are seen for everyone.

auth Config:
- Without any perm restrictions:
  - map
  - gyms
  - pokestops
  - raids
- all other perms restricted with donor role id

PS: I then tried also to restrict pokestops with donor id, but it seems it's still visible for non registered user. My map is visible for everyone visiting, no login needed. I only restrict premium features like pokemon, invasions, quests, etc

**Comment by kamieniarz** [comment]
@Fabio1988 if you fully restricted pokestops you'd need to change `sessionSecret` cause they all need to relogin otherwise they'll still see pokestops

**Comment by Fabio1988** [comment]
I also changed session secret. But it's visible to users not logged in :/ I also deleted browser cache and still pokestops filter (all, event, ar) are visible and working :/

**Comment by kamieniarz** [comment]
Oh you don't require to be logged in, right? Cause I have mine restricted to my server users only so I just removed discord guild ID from pokestops perm and it's all good after changing the sessionSecret

**Comment by Fabio1988** [comment]
I do not require login, maybe that's the edge case here. But when we have config options for event stops, or simple add it to incident perms, I am fine with that edge case 🤣

**Comment by TurtIeSocks** [comment]
Event stops only require the pokestops permissions.

**Comment by Fabio1988** [comment]
Sorry pokestops was in alwaysEnablePerms.. now it works...

Not sure how much work it is to add kecleon to invasions perms.... That's the perm were it comes from, from incidents :)

**Comment by kamieniarz** [comment]
Yeah, it's a feature request then. If not a separate perm it could be related to invasions perm

**Comment by TurtIeSocks** [comment]
Please test as it's been a long time since i've added a new permission. Also tagging @plinytheelder so he sees this.
https://github.com/WatWowMap/ReactMap/pull/634
