### ISSUE TITLE
Multi-domain configuration is not working

### ISSUE THREAD

**Issue by and189** [WatWowMap/ReactMap#649]
I configured multi-domain support as descriped in the documentation. I also copied the discord.js file to a new bb_discord.js file. After starting the map i get the following error message:

reactmap    | Failed to load bb_discord to log scanner requests, this likely means that you are using a non-updated custom strategy, please view the newly updated module.exports found at the bottom of the base strategy file:
reactmap    |  /server/src/strategies/discord.js

How i can fix it?

BR Ghost

**Comment by and189** [comment]
it has to be added as separate files in the docker-compose.yml in section volumes

**Comment by TurtIeSocks** [comment]
Glad we could solve this on discord, thank you for updating the issue accordingly.
