### ISSUE TITLE
Visual indication of a despawning mon/invasion

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/ReactMap#683]
Maybe can make a mon semi-transparent if it is going to despawn within a minute (if timer is verified)? :)

**Comment by clburlison** [comment]
Is this not solved with the Options > Show {Invasion, Pokemon} Timers?

**Comment by Mygod** [comment]
The point is to only show an indication for things that despawn within a minute instead of spamming the whole screen with timers.

**Comment by TurtIeSocks** [comment]
Resolved in #751

**Comment by clburlison** [comment]
Using my powers to reopen this one. After reviewing the implementing I think the feature is great but should be behind a user configurable flag. Kind of an accessibility concern. Sadly this means I'm agreeing with @kamieniarz.

**Comment by TurtIeSocks** [comment]
Maybe someone else could add that. It's quite easy and there are lots of PRs to reference. My remaining energy will be fixed on upgrading MUI to 5.x.

**Comment by Mygod** [comment]
Personally I think the accessibility is fine. I can see semi-transparent icons without issues even on mobile screens.

**Comment by TurtIeSocks** [comment]
Resolved in #766
