### ISSUE TITLE
Quest icons on map have weird spacing for varying sizes

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/ReactMap#686]
Steps to reproduce:

1. Find a stop with two different quests.
2. Make one quest XL and the other quest normal sized.
3. Observe the weird spacing.
<img width="110" alt="image" src="https://user-images.githubusercontent.com/3511321/230639624-1be1a0d2-ae9d-4c3e-8669-aa0cbe77c58b.png">

**Comment by TurtIeSocks** [comment]
Closing this for now because icons in their current state are too configurable (aka chaotic) to actually address until bigger changes are implemented.
