### ISSUE TITLE
Menu button to show Discord invite link

### ISSUE THREAD

**Issue by Cronick** [WatWowMap/ReactMap#688]
Don't know if this is a use-case only on my end, but the option to add a button in the front menu, where you can click on the Discord Icon and link it to an invite link for a Discord server.

![image](https://user-images.githubusercontent.com/5100210/231975368-61124e0c-9f78-4308-9360-a5a18379995d.png)

**Comment by kamieniarz** [comment]
A better option would to be just set custom link with custom icon. Maybe not just one but more + same option in drawer's settings (cause why not?)

**Comment by Cronick** [comment]
> A better option would to be just set custom link with custom icon. Maybe not just one but more + same option in drawer's settings (cause why not?)

Great point actually. To have a bit more flexability to link to additional services etc.
