### ISSUE TITLE
Bug: Weather cells disappear when a polygon is selected.

### ISSUE THREAD

**Issue by AppIe314** [WatWowMap/ReactMap#703]
**Steps to reproduce:**
1. Enable Weather
2. Enable Polygons
3. Click on a polygon

**Expected result:**
Weather cells remains visible.

**Actual result:**
All weather cells disappears.

**Comment by TurtIeSocks** [comment]
Thanks for the report, though even with the detailed steps, I'm not able to reproduce myself. Some functionality was recently changed with weather cells though so there certainly could be a bug. 

- Could you DM me your `areas.json` file so I can try it and see if something odd is going on with the area? 
- Can you also check if there are any errors/logs server side?

**Comment by clburlison** [comment]
I'm also unable to replicate this on latest. @AppIe314 are you still seeing this bug?

**Comment by TurtIeSocks** [comment]
I confirmed in DM a while back that this is all set.
