### ISSUE TITLE
Pogoinfo EOL wont be update anymore

### ISSUE THREAD

**Issue by ReuschelCGN** [WatWowMap/ReactMap#708]
`server/src/services/api/fetchRaids.js`
https://github.com/WatWowMap/ReactMap/blob/b45beeb5a09ca09ae42502d860929c00cc622bf2/server/src/services/api/fetchRaids.js#L8

Due to TSR shutdown, pogoinfo wont be update anymore. So infos needs to be collect from other source.
No idea for alternative source.....

**Comment by pjorritsma** [comment]
We could adapt the fetchRaids and invasions by using the following API (Credits Malte)
1)  https://rocket.malte.im/api/characters for invasions
2) Use https://[raw.githubusercontent.com/WatWowMap/Masterfile-Generator/master/master-latest-everything.json](https://raw.githubusercontent.com/WatWowMap/Masterfile-Generator/master/master-latest-everything.json) and filtering "invasions" out in new file
3) for raids (https://rocket.malte.im/api/raids raids) again (Credits to Malte)

Currently trying to generated the json be help would be awesome

**Comment by clburlison** [comment]
Do we actually need this raid json endpoint? Can't we just remove it is depend on the scanner database for a cleaner implementation.

As for grunt data this is currently being compiled from https://github.com/WatWowMap/event-info/ which looks to be current even with TSR being offline.

**Comment by TurtIeSocks** [comment]
Clb is correct that these endpoints are from a different "era" of ReactMap. They have been removed in #757.
