### ISSUE TITLE
Spawnpoints filter

### ISSUE THREAD

**Issue by ColBreakZ19** [WatWowMap/ReactMap#753]
Hey, would it be possible to add a filter on the Admin>Spawnpoints menu for Known/Unknown TTH ?

**Comment by TurtIeSocks** [comment]
Sure. Would be a very easy first PR. I would recommend looking at [this code](https://github.com/WatWowMap/ReactMap/blob/86bc15d90714a1d2954e0e4651b6f572c04c652b/src/components/layout/drawer/Extras.jsx#L100) to do something similar for spawnpoints 👍

**Comment by TurtIeSocks** [comment]
Resolved in #796
