### ISSUE TITLE
Unable to Connect to Webserver via golbat:9001 in Docker Container

### ISSUE THREAD

**Issue by Astu04** [WatWowMap/ReactMap#773]
**Expected Behavior**:
I expect to be able to access the web application using the hostname golbat:9001, just as I can when using the IP address http://172.25.0.13:9001.

**Actual Behavior**:
When trying to access the web application using the hostname golbat:9001, I receive an error indicating that the connection cannot be established. However, using the IP address http://172.25.0.13:9001 works perfectly fine.

```sh
[astu@map ~/RealDeviceMap]† docker exec -it reactmap sh
/home/node # wget --header="X-Golbat-Secret: xx" http://golbat:9001/api/pokemon/available
Connecting to golbat:9001 (172.25.0.13:9001)
saving to 'available'
available            100% |*************************************************************************************************************|  9288  0:00:00 ETA
'available' saved
/home/node # cat available
[{"id":32,"form":776,"count":226},{"id":204,"form":1244,"count":43},{"id":459,"form":932,"count":2},{"id":26,"form":---
```

![image](https://github.com/WatWowMap/ReactMap/assets/2796788/e8235144-e9df-496f-9c3d-c89adb0de2ff)

Using that ip it works fine.                  ^

______
```sh
/home/node # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.2
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
/home/node #
[astu@map ~/RealDeviceMap]† cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[astu@map ~/RealDeviceMap]† docker version --format '{{.Server.Version}}'
24.0.4
```

**Comment by clburlison** [comment]
For this to work as you expect you need to be running ReactMap & Golbat in docker. You should also have both services in the same docker network. 

Please see the following comment in discord and confirm if that resolves your issue. https://discord.com/channels/1083029607919386654/1083030532373352508/1131749240897552515

**Comment by Astu04** [comment]
I though my first code block would make clear that I'm running both in docker, as I can wget golbat:9001 fine from inside the ReactMap container. 
But yeah, all my scanning related dockers are within the same network in the same docker-compose.yml Close to 1k lines. 
I've confirmed it's in the same network in the yml file just in case. 

This is the error block: 
```
reactmap  | ⚠ 2023-07-21 18:46:06 [FETCH] Unable to fetch http://golbat:9001/api/pokemon/available
reactmap  |  FetchError: request to http://golbat:9001/api/pokemon/available failed, reason: getaddrinfo ENOTFOUND golbat
reactmap  |     at ClientRequest.<anonymous> (/home/node/node_modules/node-fetch/lib/index.js:1491:11)
reactmap  |     at ClientRequest.emit (node:events:525:35)
reactmap  |     at ClientRequest.emit (node:domain:489:12)
reactmap  |     at Socket.socketErrorListener (node:_http_client:502:9)
reactmap  |     at Socket.emit (node:events:513:28)
reactmap  |     at Socket.emit (node:domain:489:12)
reactmap  |     at emitErrorNT (node:internal/streams/destroy:151:8)
reactmap  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
reactmap  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
reactmap  |   type: 'system',
reactmap  |   errno: 'ENOTFOUND',
reactmap  |   code: 'ENOTFOUND'
reactmap  | }
```
I've asked yesterday for help in the discord https://discord.com/channels/907337201044582452/968137447936491570/1132022659207659520

**Comment by Astu04** [comment]
Following clburlison recommendation fixed it 
```sh
docker-compose stop reactmap && docker-compose up -d reactmap && docker-compose logs -f reactmap
```

Or maybe just... trying again. I'm not sure what happened but it's working as intended now. Sorry about the possible PEBCAK
