### ISSUE TITLE
Multiple Choice Quest Reward Selection

### ISSUE THREAD

**Issue by unseenmagik** [WatWowMap/ReactMap#782]
A request to change the options for multi-reward quests. 
At the moment we can only filter by ALL or one option. 
A possible multiple choice option implementation.

![image](https://github.com/WatWowMap/ReactMap/assets/30931287/742f5e1d-6503-408c-bf8b-ec413c2b3036)

**Comment by kamieniarz** [comment]
Oh yeah, my map users also requested this today

**Comment by TurtIeSocks** [comment]
Resolved in #790
