### ISSUE TITLE
can't disable global mon slider filters

### ISSUE THREAD

**Issue by matt-yml** [WatWowMap/ReactMap#783]
all or just hundos are still going through when they should be disabled.
user wants to just see all ivs of a couple mon (e.g. tyrunt amaura)

possible uicons misconfiguration bug suggested by @TurtIeSocks 
https://discord.com/channels/907337201044582452/968137447936491570/1134482754256506972

![image](https://github.com/WatWowMap/ReactMap/assets/41926716/c780d837-5db3-45b7-bf84-5eb81f3527ee)
![image](https://github.com/WatWowMap/ReactMap/assets/41926716/9a1df5a0-43ac-4dc5-804e-3a95988f69d7)

**Comment by clburlison** [comment]
Resolved in discord. https://discord.com/channels/907337201044582452/968137447936491570/1134497069772578856
