### ISSUE TITLE
Move Spawnpoints out of Admin tab

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#804]
I think Admin tab makes no sense for such feature. I think Spawnpoints should be moved to Pokemon tab between gender and options

**Comment by TurtIeSocks** [comment]
Spawnpoints for sure do not belong in the Pokemon tab. I have no plans to write this as I think it should be exactly where it is, but if someone else writes it, it should be configurable. I'll leave this open for one month until marking it as `Close as not planned`
