### ISSUE TITLE
Scan Zone cooldown only counts down if the map is open

### ISSUE THREAD

**Issue by unseenmagik** [WatWowMap/ReactMap#815]
When a cooldown value is used for Scan Next, the cooldown time is calculated correctly and set for the user.
However, the countdown of the cooldown time only counts down then the map is open in a browser. 
If the map is closed (browser, tab or app) the cooldown time does not continue to count down. 
The cooldown time needs to continue to countdown if the browser / tab is closed.

**Comment by Pogodenhelder** [comment]
totally 100% confirmed..

**Comment by TurtIeSocks** [comment]
Resolved in #810
