### ISSUE TITLE
Route details not showing in popup

### ISSUE THREAD

**Issue by svenberg** [WatWowMap/ReactMap#824]
I'm not able to see any detailed information in the routes popup.
I'm on develop, latest commit (9f5ff6221ddb66d1fdea3d512742cb76bf5121bf), pulled + yarn install + RM restart.

Looking in the golbat.route table I can see names and other details. In the picture below you see how it looks, and the other pic shows the database for that specific route as well.

![image](https://github.com/WatWowMap/ReactMap/assets/46693744/6be67c71-1d8a-418c-aff6-9a7b4e398849)
![image](https://github.com/WatWowMap/ReactMap/assets/46693744/a6363c91-05e4-4db2-8b9b-6823e49bf414)

/Crippe

**Comment by TurtIeSocks** [comment]
Can you check network transfers in the browser? F12 to open the console, hit networking tab, then check the `/graphql` requests. Route data is delivered in two parts. The first showing all of the start and stop locations + the route. The second filling in all of the data when the popup is opened. I confirmed it's still working, even after joddie's MAD PRs were merged so it shouldn't be that... but check the networking to see if the Route requests are failing for some reason.

**Comment by svenberg** [comment]
I got it working again - the bug seem to be when you have **two** route tables to pull data from. There are duplicate routes pulled because the tables includes the same routes at some places.
Both tables have the data with details.

I tried truncating one table, it would still not show details. As soon as I remove one of the two schemas it starts to work.

**Comment by svenberg** [comment]
I'll check the networking in the browser

**Comment by TurtIeSocks** [comment]
That seems very plausible then. I've never tested the second query with two databases to choose from. I'll do that later.

**Comment by svenberg** [comment]
I see both graphql requests but I'm not sure how to follow them, there's no clear data in there to look at. Even when having one database to pull from and the popup is populated correctly, the content is not in clear text.

Thanks for checking this later, I appreciate it.

**Comment by TurtIeSocks** [comment]
I've confirmed and fixed this on #810, I'm gearing up to merge that large PR in soon-ish.

**Comment by TurtIeSocks** [comment]
@svenberg please confirm if this is fixed in latest develop

**Comment by TurtIeSocks** [comment]
Closing as I believe this has been resolved. Feel free to open again if not.
