### ISSUE TITLE
Coords option not working

### ISSUE THREAD

**Issue by unseenmagik** [WatWowMap/ReactMap#842]
There was the option added for the client to be able to enable or disable coords in the popup for the mon, pokestop and gym, but these appear to not be an option any longer. Possibly with the re-write they have been lost!

**Comment by acocalypso** [comment]
Can't confirm that issue. Latest dev everything is working fine. Have you check in the menu Pokemon -> options -> show cords?

**Comment by unseenmagik** [comment]
> Can't confirm that issue. Latest dev everything is working fine. Have you check in the menu Pokemon -> options -> show cords?

I have checked the options but I do not see it there

<img width="345" alt="image" src="https://github.com/WatWowMap/ReactMap/assets/30931287/10e78667-08c9-4cf0-9c0c-b91505ab7e4d">
<img width="345" alt="image" src="https://github.com/WatWowMap/ReactMap/assets/30931287/d308ce5f-0ce2-4324-a2e5-597a9514b478">

**Comment by TurtIeSocks** [comment]
You have to enable them in the config first before you can see them in the menus.

**Comment by unseenmagik** [comment]
> You have to enable them in the config first before you can see them in the menus.

Well, there we go... Thank you. Ill get my coat now ;-)
