### ISSUE TITLE
Custom colours (primary/secondary) not functioning after #832 (develop)

### ISSUE THREAD

**Issue by roundaboutluke** [WatWowMap/ReactMap#850]
As per the title, primary/secondary custom colours set in local.json are no longer applying after #832 on develop. No notable logging.

**Comment by TurtIeSocks** [comment]
Can you share your `map.theme` object in your `local.json` so I can double check it? I just tried it in mine and it seems to be okay.

**Comment by roundaboutluke** [comment]
My bad - looks like a lot of the layout changed for this as mine was still under map, within misc but resolved by bringing my config up to date. 🙇‍♂️ Will check this in future first next time :)

**Comment by TurtIeSocks** [comment]
Ah, the config json layout hasn't changed but the internal behavior of the map config object has. Previously it was lazily all merged together, so it would have ended up being "accidentally" valid. Thanks for verifying it works!
