### ISSUE TITLE
Auth flow issue using Discord (maybe others)

### ISSUE THREAD

**Issue by tchavei** [WatWowMap/ReactMap#866]
If you protect your map with discord authentication flow and restrict the map to be only available for users in [allowed guild], when a user logins and isn't part of allowed guilds, the Map hangs showing the loading animation. On the address bar one can see https://serverurl/blocked/message%3Daccess_denied but the user is never clearly informed that his auth failed in some way. There should be a landing page option to where the user is redirected in case he's denied access to inform him of whatever the map owner wishes.

**Comment by TurtIeSocks** [comment]
#872 if you want to test it

**Comment by TurtIeSocks** [comment]
Resolved
