### ISSUE TITLE
Hide feature crashes the map

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#868]
If I hide specific item (pokemon, pokestop, gym) it crashes the map. One of the errors below. Red error appears at first, map refreshes few times by itself and ends up with black screen. Map restart helps 

![IMG_20231022_234615](https://github.com/WatWowMap/ReactMap/assets/9063907/a14220da-25c3-4af2-84e3-645ba15089b3)
![Screenshot_2023-10-22-23-45-57-60_2be7a90e9173f6e9195b7efda4cb035b](https://github.com/WatWowMap/ReactMap/assets/9063907/989c927e-42e2-403a-a361-de26ac1ab699)

```
[31m✖[39m 2023-10-21 19:44:04 [97m[CLIENT][39m {
  client_version: '1.26.0',
  server_version: '1.26.0',
  username: 'EDITED',
  client_id: 'da1c71fe-r2m4-61a0-a028-35f7a7d0b62a',
  nginx_id: undefined,
  trace: "TypeError: Cannot read properties of null (reading 'key')\n" +
    '    at https://EDITED/1-26-0-96514e50.js:1972:3261\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at https://EDITED/1-26-0-96514e50.js:1972:3232\n' +
    'Sm (../node_modules/react-dom/cjs/react-dom.production.min.js:244:331)\n' +
    'tu (../node_modules/react-dom/cjs/react-dom.production.min.js:286:110)\n' +
    'e3 (../node_modules/react-dom/cjs/react-dom.production.min.js:283:408)\n' +
    'Cs (../node_modules/react-dom/cjs/react-dom.production.min.js:281:397)\n' +
    'TC (../node_modules/react-dom/cjs/react-dom.production.min.js:273:438)\n' +
    'is (../node_modules/react-dom/cjs/react-dom.production.min.js:127:104)\n' +
    '    at https://EDITED/vendor-b3f0d915.js:8:34283'
}
```

**Comment by TurtIeSocks** [comment]
This is on `develop`?

**Comment by kamieniarz** [comment]
Yes, latest develop

**Comment by TurtIeSocks** [comment]
Interesting. There also appears to be something wrong with your error reporting, as it's not being de-minified. It should be reporting the error with the exact line in the exact file that it's failing on... are you changing anything when it comes to producing the js maps? From the root of your ReactMap repo can you run `ls ./dist`?

**Comment by kamieniarz** [comment]
I'm not changing anything

```
$ ls ./dist
1-26-0-342f20ac.js      favicon.ico  index-48b84564.css  index-a2e173c3.js.map  index.html  robots.txt          vendor-b3f0d915.js.map
1-26-0-342f20ac.js.map  images       index-a2e173c3.js   index-f62b2219.js.map  locales     vendor-b3f0d915.js
```

**Comment by kamieniarz** [comment]
@TurtIeSocks sorry, I'm dumb. I was on latest but I totally forgot I switched to `super-cluster` branch 🤦‍♂️ Latest develop is fine again ;)
