### ISSUE TITLE
Sponsored Forts shouldn't be count in the total POI number of a cell

### ISSUE THREAD

**Issue by ColBreakZ19** [WatWowMap/ReactMap#870]
Hi there ! 

Sponsored Forts shouldn't count in the total POI number of a cell, since they don't have any impact on it.

I checked my database and looks like I sponsored forts are ones with partner_ID not NULL.
It also seems that they don't have an impact on fort apparition (20m rule is useless & new fort can spawn even if there is one sponsored gym on the S17 cell).
=> Exclude sponsored fort in L14 cell total count, and also from the "Points of Interest" toggle.

Pokestops that are used for pokemon showcase can't be turned into a gym, even if there isn't a sowcase on it. 
It would now be interesting to have a visual information of either the pokestop is used for showcase or not.

=> Golbat Would it be possible keep in the database that a stop is used for pokemon showcases, 
=> ReactMap aware the user on fort pop-up ?

**Comment by TurtIeSocks** [comment]
I talked with some of my heavy Wayfarer users and they concluded that sponsored stops do actually count towards the number of POIs, however, this only syncs every 1-3 months so it may not be immediately apparent that it does count. However, in an upcoming PR I will allow users to turn off sponsored/partner stops to set it how they want to view it.

**Comment by TurtIeSocks** [comment]
Resolved
