### ISSUE TITLE
[Bug] Substitute doll everywhere

### ISSUE THREAD

**Issue by lenisko** [WatWowMap/ReactMap#878]
When RM is left in background for a while, every icon turn to Substitute doll.

Apparently it started this month around 16th or earlier.

Issue confirmed on Firefox, Chrome on Windows and iOS. Most likely not browser issue?

Map turns out to that after a while:
![before](https://github.com/WatWowMap/ReactMap/assets/10072920/b68cb242-98db-40d6-a232-053247dbbc27)

And after manual refresh things go back:
![after](https://github.com/WatWowMap/ReactMap/assets/10072920/286ebbf0-d338-4865-a60b-3817404e8dfe)

**Comment by notheowner** [comment]
Has anyone confirmed this is not a Cloudflare issue?

**Comment by TurtIeSocks** [comment]
This is 100% a GitHub issue. Everyone who self hosts images has confirmed it's fine.

**Comment by zack-kyria** [comment]
> Has anyone confirmed this is not a Cloudflare issue?

it is not. people w/o CF on disc have confirmed they got it as well. As turtle said it is prolly GH issue as I also had gh lags and other issues on small projects of mine

**Comment by lenisko** [comment]
Yeah, I swapped from GH to self-host behind CF and getting those as well.

**Comment by clburlison** [comment]
Just another data point. I left my map open over night. Checked this morning and icons were fully functional. Images are self hosted.

**Comment by lenisko** [comment]
Doubt it's related to CF, GH or even browsers itself... Maybe some packages been upgraded on RM side? Or icons handling has changed?

**Comment by notheowner** [comment]
I cannot reproduce it with the latest commit bb9cbde in `icons-fix `branch.
Phone and desktop. If anyone else wants to try.

**Comment by lenisko** [comment]
@TurtIeSocks Ha!

**Comment by TurtIeSocks** [comment]
> @TurtIeSocks Ha!

Still been fine for me. Just tired of the whining 😘

**Comment by TurtIeSocks** [comment]
Resolved
