### ISSUE TITLE
[Bug] Button UI inconsistency with scanZone/scanNext 

### ISSUE THREAD

**Issue by roundaboutluke** [WatWowMap/ReactMap#890]
When using scanZone/scanNext the buttons don’t follow custom colour schemes and also cause the buttons above to turn transparent. 

images show this better than I could ever hope to describe - 
![IMG_0817](https://github.com/WatWowMap/ReactMap/assets/10819615/24cfe060-dd55-4647-a187-504e81eb972e)
![IMG_0818](https://github.com/WatWowMap/ReactMap/assets/10819615/6e549628-6123-414a-b0fb-5c49630b7e8c)

**Comment by TurtIeSocks** [comment]
Fixed in #900. The transparent icons are intentional though to indicate that they're disabled when one of the Scan on Demand are enabled.
