### ISSUE TITLE
Can't filter out nests with mons/h > 100

### ISSUE THREAD

**Issue by kamieniarz** [WatWowMap/ReactMap#908]
Currently nests filter allows to filter in range 0-100 only. Even if set eg. 0-500 in default filter it still allows to filter out max 100 so I can't filter out eg. 100-500

**Comment by TurtIeSocks** [comment]
<img width="296" alt="Screenshot 2024-01-05 at 10 58 13 AM" src="https://github.com/WatWowMap/ReactMap/assets/58572875/39f0988f-5ede-46f8-aca1-46756fbae24d">

What am I missing here?

**Comment by kamieniarz** [comment]
How did you do that? I can't go beyond 100

**Comment by TurtIeSocks** [comment]
```json
    "nests": {
      "enabled": false,
      "polygons": false,
      "pokemon": false,
      "avgFilter": [
        0,
        500
      ]
    },
```

**Comment by kamieniarz** [comment]
No idea why I had these ranges in config in one line and proly that's why it didin't work for me 🤔 Thanks
