### ISSUE TITLE
Bug with Alerts Rockruff Dusk Form for raids

### ISSUE THREAD

**Issue by clburlison** [WatWowMap/ReactMap#912]
Testing on `develop` commit 41cb8f7cb31f14550d4bb5b59498b829fda6cc47 which is pretty recent

1. Open Poracle alert
2. Select Raid
3. Search for Rockruff Dust Form
4. Click the checkbox for Dusk form and save
5. It is saved to Poracle as Normal form

Tried this a few different ways, disabling the "All Form" toggle before clicking toggle. Each time it was saved as Normal form. This is working for Pokemon alerts. Was only able to replicate using the Raid alert type.

Sadly that's all I'm able to test/provide atm. Hopefully enough info to replicate 😓

**Comment by TurtIeSocks** [comment]
Resolved in https://github.com/KartulUdus/PoracleJS/pull/889
