### ISSUE TITLE
Error setting advanced poracle notifications for grunts

### ISSUE THREAD

**Issue by mkllrtxn** [WatWowMap/ReactMap#926]
It consistently happens when trying to setup advanced poracle notifications for grunts.
Steps to reproduce:

- Open menu clicking in the bell icon
- Go to Rocket tab
- Click in the advanced options of any grunt type

Same steps for other categories are working fine

![image](https://github.com/WatWowMap/ReactMap/assets/53058001/d94dd730-6f2d-4022-bb12-48ed130da569)

**Comment by notheowner** [comment]
I can reproduce this on my end as well

**Comment by mkllrtxn** [comment]
I am on latest develop and still experience it…

**Comment by mkllrtxn** [comment]
`,
  server_version: '1.29.0-develop.9',
  username: 'ohmaikgosh',
  client_id: '3f77a57c-r2m4-646d-8675-02fc1c74ea7f',
  nginx_id: undefined,
  trace: 'pt@/1-29-0-develop-9-eed5127f.js:2101:182\n' +
    'Qg@/1-29-0-develop-9-eed5127f.js:2112:5335\n' +
    'Tb@/vendor-f1640e5b.js:6:19539\n' +
    'N0@/vendor-f1640e5b.js:8:3155\n' +
    'mk@/vendor-f1640e5b.js:8:39812\n' +
    'i3@/vendor-f1640e5b.js:8:39740\n' +
    'Gh@/vendor-f1640e5b.js:8:39593\n' +
    'G0@/vendor-f1640e5b.js:8:35955\n' +
    'CC@/vendor-f1640e5b.js:8:36762\n' +
    'CC@[native code]\n' +
    'as@/vendor-f1640e5b.js:6:3280\n' +
    '@/vendor-f1640e5b.js:8:34285'
}
`

**Comment by notheowner** [comment]
You can close this issue.
