### ISSUE TITLE
pokestops shows quests on all stops, if you enable all pokestops, not lige gyms

### ISSUE THREAD

**Issue by skelgaard** [WatWowMap/ReactMap#951]
That sometimes make users not knowing why they can't filter.. 
maybe should be more like with gyms ?

**Comment by Fabio1988** [comment]
How is gyms filter different?
That's supposed like that, always have been :)

**Comment by skelgaard** [comment]
if i have filteret on which raids i want showed, and i click on all gyms, it shows the gyms, but not the raids on them, but on stops, if i press show all, it shows me all quests on all stops, eventhough i have filtered them out

**Comment by TurtIeSocks** [comment]
This is intentional behavior for the time being.
