### ISSUE TITLE
Pokemon don’t appear on map

### ISSUE THREAD

**Issue by Chombiy7** [WatWowMap/ReactMap#999]
Hi! Newbie here. Why does pokemon occasionally missing from the map? I tried enabling the gym, quest from pokestop, etc and there is no issue with them. Only the pokemon that always happened. Thank you in advance! This is the example
![IMG_4205](https://github.com/WatWowMap/ReactMap/assets/166082723/eedbd3a9-4673-44aa-8b80-580d59291e87)

**Comment by TurtIeSocks** [comment]
@Chombiy7 hi there! You'll likely want to check with your local mapper, as this is the repository for the map code in general that's used all around the world :)
